server:
  servlet:
    context-path: /api

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/amigoscodemo
      username: postgres
      password: mysecretpassword
      maximum-pool-size: 30


#  server.servlet.context-path=/api
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/amigoscodemo
#spring.datasource.username=postgres
#spring.datasource.password=mysecretpassword